[package]
name = "cblang"
edition = "2024"
description = "Implementation of the C/Buoy language and Jib code export"
version.workspace = true
authors.workspace = true
documentation.workspace = true

[dependencies]
regex = "1"
jib-cpu = { workspace = true }
jib-asm = { workspace = true }
cbfs-lib = { workspace = true, optional = true }

[features]
default = ["cbfs"]
cbfs = ["dep:cbfs-lib"]
