[package]
name = "jib-cpu"
edition = "2024"
description = "Jib processor implementation and associated common computer devices"
version.workspace = true
authors.workspace = true
documentation.workspace = true

[dependencies]
chrono = { workspace = true, optional = true }
circ-buff = { workspace = true }

[features]
default = ["rtcdev"]
std = []
rtcdev = ["std", "dep:chrono"]
