[package]
name = "jib-os-image"
edition = "2024"
version.workspace = true
authors.workspace = true
documentation.workspace = true

[dependencies]
cbfs-lib = { path = "../../cbfs/cbfs-lib", version = "*", default-features = false }

[build-dependencies]
jib-os.workspace = true
cbfs-lib = { path = "../../cbfs/cbfs-lib", version = "*", default-features = false }
