[package]
name = "jib-term"
edition = "2024"
description = "Terminal implementation of Jib computer for interactive use"
version.workspace = true
authors.workspace = true
documentation.workspace = true

[dependencies]
jib-cpu = { workspace = true }
jib-computer = { workspace = true }
clap = { workspace = true }
cbfs-lib = { workspace = true }
ctrlc = "3.5"
