[package]
name = "jib-os"
edition = "2024"
version.workspace = true
authors.workspace = true
documentation.workspace = true

[dependencies]
jib-cpu = { workspace = true }
#jib-asm = { workspace = true }
jib-computer.workspace = true
cblang = { workspace = true }
cbfs-lib = { path = "../../cbfs/cbfs-lib", version = "*", default-features = false }
#circ-buff = { workspace = true }

[build-dependencies]
chrono = { workspace = true }
