[package]
name = "jib-computer"
edition = "2024"
description = "Implementation of a standard Jib computer"
version.workspace = true
authors.workspace = true
documentation.workspace = true

[dependencies]
jib-cpu = { workspace = true }
jib-asm = { workspace = true }
cblang = { workspace = true }
cbfs-lib = { path = "../../cbfs/cbfs-lib", version = "*", default-features = false }
circ-buff = { workspace = true }

[build-dependencies]
chrono = { workspace = true }
