[package]
name = "cbc"
edition = "2024"
description = "C/Buoy compiler for the Jib processor"
version.workspace = true
authors.workspace = true
documentation.workspace = true

[dependencies]
cblang = { path = "../cblang", version = "*", features = ["cbfs"] }
jib-asm = { workspace = true }
clap = { workspace = true }
