[package]
name = "cbfs-compat"
edition = "2024"
description = "Compatibility library to export CBFS functions via a C API"
version.workspace = true
authors.workspace = true
documentation.workspace = true

 [lib]
 crate-type = ["cdylib", "staticlib"]

[dependencies]
cbfs-lib = { workspace = true }
chrono = { version = "*" }

[build-dependencies]
cbindgen = "0.29"
cbfs-lib = { workspace = true }
