name: Compiled

on:
  push:
    tags:
      - "v*"
      - "test/compiled"

permissions:
  contents: write

jobs:
  linux:
    runs-on: ${{ matrix.host }}
    strategy:
      matrix:
        include:
          - os: fedora
            host: ubuntu-latest
            version: 44
            pkgmgr: dnf
            toolchain: x86_64-unknown-linux-gnu
            arch: x86_64
          - os: debian
            host: ubuntu-latest
            version: 13
            pkgmgr: apt
            toolchain: x86_64-unknown-linux-gnu
            arch: x86_64
          - os: ubuntu
            host: ubuntu-latest
            version: 22.04
            pkgmgr: apt
            toolchain: x86_64-unknown-linux-gnu
            arch: x86_64
          - os: ubuntu
            host: ubuntu-latest
            version: 24.04
            pkgmgr: apt
            toolchain: x86_64-unknown-linux-gnu
            arch: x86_64
          - os: ubuntu
            host: ubuntu-latest
            version: 26.04
            pkgmgr: apt
            toolchain: x86_64-unknown-linux-gnu
            arch: x86_64
          - os: alpine
            host: ubuntu-latest
            version: 3.24
            pkgmgr: apk
            toolchain: x86_64-unknown-linux-musl
            arch: x86_64
          - os: fedora
            host: ubuntu-24.04-arm
            version: 44
            pkgmgr: dnf
            toolchain: aarch64-unknown-linux-gnu
            arch: aarch64
          - os: debian
            host: ubuntu-24.04-arm
            version: 13
            pkgmgr: apt
            toolchain: aarch64-unknown-linux-gnu
            arch: aarch64
          - os: ubuntu
            host: ubuntu-24.04-arm
            version: 24.04
            pkgmgr: apt
            toolchain: aarch64-unknown-linux-gnu
            arch: aarch64
          - os: ubuntu
            host: ubuntu-24.04-arm
            version: 26.04
            pkgmgr: apt
            toolchain: aarch64-unknown-linux-gnu
            arch: aarch64

    container:
      image: ${{ matrix.os }}:${{ matrix.version }}

    steps:
      - uses: laverdet/alpine-arm64@v1
        if: ${{ matrix.host.arch == 'arm64' && matrix.os == 'alpine' }}

      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Install dependencies (apt)
        if: ${{ matrix.pkgmgr == 'apt' }}
        run: |
          apt-get update
          apt-get install -y pkg-config build-essential libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0 libwayland-dev libxkbcommon-dev libfuse3-dev cmake ninja-build curl

      - name: Install dependencies (dnf)
        if: ${{ matrix.pkgmgr == 'dnf' }}
        run: |
          dnf update -y
          dnf install -y g++ gcc clang clang-devel clang-tools-extra libxkbcommon-devel pkg-config openssl-devel libxcb-devel gtk3-devel atk fontconfig-devel wayland-devel fuse3-devel cmake ninja-build curl

      - name: Install dependencies (apk)
        if: ${{ matrix.pkgmgr == 'apk' }}
        run: |
          apk update
          apk add g++ gcc cmake ninja fuse3-dev git curl bash

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.toolchain }}

      - name: Test
        run: cargo test --workspace

      - name: Build the executable
        run: |
          cargo build --release --target ${{ matrix.toolchain }} -p visual-jib
          cargo build --release --target ${{ matrix.toolchain }} -p cbfs-util
          cargo build --release --target ${{ matrix.toolchain }} -p cbc
          cargo build --release --target ${{ matrix.toolchain }} -p jib-term

      - name: Build FUSE Driver
        run: |
          cargo install --locked cbindgen
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCARGO_TARGET=${{ matrix.toolchain }} -GNinja
          ninja -C build

      - name: Copy executables
        run: |
          mkdir dist
          cp target/${{ matrix.toolchain }}/release/visual-jib dist/visual-jib
          cp target/${{ matrix.toolchain }}/release/cbfs-util dist/cbfs-util
          cp target/${{ matrix.toolchain }}/release/cbc dist/cbc
          cp target/${{ matrix.toolchain }}/release/jib-term dist/jib-term
          cp visual-jib/desktop/visual-jib.desktop dist/visual-jib.desktop
          cp doc/images/logo.svg dist/visual-jib.svg
          cp build/cbfs/cbfs-fuse/cbfs dist/cbfs

      - name: Package binary
        run: tar -czvf solarium-${{ matrix.os }}-${{ matrix.version }}-${{ matrix.arch }}.tar.gz -C dist visual-jib cbfs cbfs-util cbc jib-term visual-jib.desktop visual-jib.svg

      - name: Upload release binaries
        uses: actions/upload-artifact@v7
        with:
          name: solarium-${{ matrix.os }}-${{ matrix.version }}-${{ matrix.arch }}.tar.gz
          path: solarium-${{ matrix.os }}-${{ matrix.version }}-${{ matrix.arch }}.tar.gz

  freebsd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Build project
        id: vm
        uses: vmactions/freebsd-vm@v1
        with:
          release: "15.0"
          sync: rsync
          prepare: pkg install -y cmake fusefs-libs3 rust ninja
          run: |
            cargo test --workspace
            cargo build --release --target x86_64-unknown-freebsd -p cbfs-util
            cargo build --release --target x86_64-unknown-freebsd -p cbc
            cargo build --release --target x86_64-unknown-freebsd -p jib-term
            cargo build --release --target x86_64-unknown-freebsd -p visual-jib
            cargo install --locked cbindgen
            export PATH="$PATH:/root/.cargo/bin"
            cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCARGO_TARGET=x86_64-unknown-freebsd -GNinja
            ninja -C build
            mkdir dist
            cp target/x86_64-unknown-freebsd/release/cbfs-util dist/cbfs-util
            cp target/x86_64-unknown-freebsd/release/cbc dist/cbc
            cp target/x86_64-unknown-freebsd/release/jib-term dist/jib-term
            cp target/x86_64-unknown-freebsd/release/visual-jib dist/visual-jib
            cp visual-jib/desktop/visual-jib.desktop dist/visual-jib.desktop
            cp doc/images/logo.svg dist/visual-jib.svg
            cp build/cbfs/cbfs-fuse/cbfs dist/cbfs
            tar -czvf solarium-freebsd-15-x86_64.tar.gz -C dist cbfs cbfs-util cbc jib-term visual-jib visual-jib.desktop visual-jib.svg
            rm -rf target build

      - name: Upload release binaries
        uses: actions/upload-artifact@v7
        with:
          name: solarium-freebsd-15-x86_64.tar.gz
          path: solarium-freebsd-15-x86_64.tar.gz

  macos:
    runs-on: macos-latest
    steps:
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin,aarch64-apple-darwin

      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Install macFUSE
        run: |
          /usr/bin/curl -L https://github.com/macfuse/macfuse/releases/download/macfuse-5.3.3/macfuse-5.3.3.dmg -o macfuse.dmg
          diskutil image attach macfuse.dmg
          sudo /usr/sbin/installer -pkg "/Volumes/macFUSE/Install macFUSE.pkg" -target /
          diskutil unmount /Volumes/macFUSE
          rm macfuse.dmg

      - name: Test
        run: cargo test --workspace

      - name: Build the executables
        run: |
          cargo build --release --target x86_64-apple-darwin --target aarch64-apple-darwin -p visual-jib
          cargo build --release --target x86_64-apple-darwin --target aarch64-apple-darwin -p cbfs-util
          cargo build --release --target x86_64-apple-darwin --target aarch64-apple-darwin -p cbc
          cargo build --release --target x86_64-apple-darwin --target aarch64-apple-darwin -p jib-term

      - name: Build FUSE Driver
        run: |
          cargo install --locked cbindgen
          cmake -S . -B build/x64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCARGO_TARGET=x86_64-apple-darwin -GNinja
          ninja -Cbuild/x64
          cmake -S . -B build/arm64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES=arm64 -DCARGO_TARGET=aarch64-apple-darwin -GNinja
          ninja -Cbuild/arm64

      - name: Create a fat executable for all targets
        run: |
          mkdir dist
          lipo -create -output dist/visual-jib target/x86_64-apple-darwin/release/visual-jib target/aarch64-apple-darwin/release/visual-jib
          lipo -create -output dist/cbfs-util target/x86_64-apple-darwin/release/cbfs-util target/aarch64-apple-darwin/release/cbfs-util
          lipo -create -output dist/cbc target/x86_64-apple-darwin/release/cbc target/aarch64-apple-darwin/release/cbc
          lipo -create -output dist/jib-term target/x86_64-apple-darwin/release/jib-term target/aarch64-apple-darwin/release/jib-term
          lipo -create -output dist/cbfs build/x64/cbfs/cbfs-fuse/cbfs build/arm64/cbfs/cbfs-fuse/cbfs

      - name: Create a bundle
        run: |
          cargo install cargo-packager --locked
          cargo packager --release --target aarch64-apple-darwin --packages visual-jib -f app
          cp dist/visual-jib target/aarch64-apple-darwin/release/VisualJib.app/Contents/MacOS/visual-jib
          cp -r target/aarch64-apple-darwin/release/VisualJib.app dist

      - name: Package binary
        run: |
          tar -czvf solarium-macos.tar.gz -C dist cbfs-util cbc jib-term VisualJib.app cbfs

      - name: Upload release binaries
        uses: actions/upload-artifact@v7
        with:
          name: solarium-macos.tar.gz
          path: solarium-macos.tar.gz

  windows:
    runs-on: ${{ matrix.host }}
    strategy:
      matrix:
        include:
          - host: windows-2025-vs2026
            arch: x86_64
            msarch: amd64
            msvc: C:\Program Files\Microsoft Visual Studio\18\Enterprise
          - host: windows-11-arm
            arch: aarch64
            msarch: arm64
            msvc: C:\Program Files\Microsoft Visual Studio\2022\Enterprise
    steps:
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.arch }}-pc-windows-msvc

      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Test
        run: cargo test --workspace

      - name: Build the executable
        run: |
          cargo build --release --target ${{ matrix.arch }}-pc-windows-msvc -p visual-jib
          cargo build --release --target ${{ matrix.arch }}-pc-windows-msvc -p cbfs-util
          cargo build --release --target ${{ matrix.arch }}-pc-windows-msvc -p cbc
          cargo build --release --target ${{ matrix.arch }}-pc-windows-msvc -p jib-term

      - name: Install WinFSP
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://github.com/winfsp/winfsp/releases/download/v2.1/winfsp-2.1.25156.msi" -OutFile ".\winfsp-2.1.25156.msi"
          $file = "winfsp-2.1.25156.msi"
          $log = "install.log"
          $procMain = Start-Process "msiexec" "/i `"$file`" ADDLOCAL=all /qn /l*! `"$log`"" -NoNewWindow -PassThru
          $procLog = Start-Process "powershell" "Get-Content -Path `"$log`" -Wait" -NoNewWindow -PassThru
          $procMain.WaitForExit()
          $procLog.Kill()

      - name: Build FUSE Driver
        run: |
          Import-Module "${{ matrix.msvc }}\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"
          Enter-VsDevShell -VsInstallPath "${{ matrix.msvc }}" -SkipAutomaticLocation -DevCmdArguments "-arch=${{ matrix.msarch }}"
          cargo install --locked cbindgen
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCARGO_TARGET=${{ matrix.arch }}-pc-windows-msvc -DCBFS_WIN_ARCH=${{ matrix.msarch }} -GNinja
          ninja -C build

      - name: Copy binaries
        shell: pwsh
        run: |
          New-Item -Path . -Name dist -ItemType Directory
          Copy-Item target\${{ matrix.arch }}-pc-windows-msvc\release\visual-jib.exe dist
          Copy-Item target\${{ matrix.arch }}-pc-windows-msvc\release\cbfs-util.exe dist
          Copy-Item target\${{ matrix.arch }}-pc-windows-msvc\release\cbc.exe dist
          Copy-Item target\${{ matrix.arch }}-pc-windows-msvc\release\jib-term.exe dist
          Copy-Item build\cbfs\cbfs-fuse\cbfs.exe dist

      - name: Update icon
        shell: pwsh
        if: ${{ matrix.msarch != 'arm64' }}
        run: |
          magick -density 300 -define icon:auto-resize=256,128,96,64,48,32,16 -background none doc\images\logo.svg doc\images\logo.ico
          Invoke-WebRequest -Uri "https://github.com/electron/rcedit/releases/download/v1.1.1/rcedit-x64.exe" -OutFile ".\rcedit-x64.exe"
          .\rcedit-x64.exe dist\visual-jib.exe --set-icon doc\images\logo.ico

      - name: Package artifacts
        shell: pwsh
        run: |
          Compress-Archive -Path dist\* -DestinationPath solarium-windows-${{ matrix.arch }}.zip -Force

      - name: Upload release binaries
        uses: actions/upload-artifact@v7
        with:
          name: solarium-windows-${{ matrix.arch }}.zip
          path: solarium-windows-${{ matrix.arch }}.zip

  common:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive texlive-font-utils

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu

      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Build the documentation
        working-directory: doc
        run: |
          pdflatex isa.tex
          pdflatex isa.tex

      - name: Upload documentation
        uses: actions/upload-artifact@v7
        with:
          name: isa.pdf
          path: doc/isa.pdf

      - name: Upload license
        uses: actions/upload-artifact@v7
        with:
          name: LICENSE
          path: LICENSE

      - name: Generate hard disk image
        run: cargo run -p jib-term -- -e hd.cbfs

      - name: Upload hard disk image
        uses: actions/upload-artifact@v7
        with:
          name: hd.cbfs
          path: hd.cbfs

  release:
    name: Publish release
    needs: [macos, linux, windows, freebsd, common]
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref_name, 'v') && github.ref_type == 'tag' }}

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: release-artifacts
          merge-multiple: true

      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          files: release-artifacts/*
